### ISSUE TITLE
wrong result?

### ISSUE THREAD

**Issue by ischlag** [piantado/pychuriso#3]
I have just started to play around with pychuriso and I've run a few examples that I can understand. In this case, I ran the even-odd.churiso file using this command: 

`python3 src/run.py --search-basis=KBCW domains/even-odd.churiso > output/even-d_KBCW.txt 2> output/even-odd_KBCW.log --max-find=20`

I'm a little puzzled by the output. E.g. this part is the first solution it finds:

```
(...)
################################################################################
0 66 77 -84.43663253763222
True := (K K)
one := K
succ := K
two := (K K)
three := (K (K K))
four := (K (K (K K)))
even := ((((S ((S (K ((S (K S)) K))) S)) (K K)) ((S S) (S K))) K)
odd := (((S S) (S K)) (((S S) (S K)) K))
show (succ four) -> (K (K (K (K K)))) == {}
show (succ (succ four)) -> (K (K (K (K (K K))))) == {}
show (succ (succ (succ four))) -> (K (K (K (K (K (K K)))))) == {}
show (even (succ four)) -> (K (K K)) == {three}
show (even (succ (succ four))) -> (K (K (K K))) == {four}
show (even (succ (succ (succ four)))) -> (K (K (K (K K)))) == {}
show (odd (succ four)) -> (K (K (K K))) == {four}
show (odd (succ (succ four))) -> (K (K (K (K K)))) == {}
show (odd (succ (succ (succ four)))) -> (K (K (K (K (K K))))) == {}
################################################################################
(...)
```

There is a few things I don't understand:

1.) What are the first 4 numbers. The first seems to be the solution index, and the last one something that is named a "catalan prior" of which I don't find any information online.

2.) Why does `show (odd (succ four))` result in `(K (K (K K)))` i.e. "four"? Shouldn't the result be the definition of "true"? Is this a mistake?

3.) Why does the algorithm keep searching for more (longer) solutions, is there not an infinite number of them?

**Comment by piantado** [comment]
Sorry for the lack of documentation! 

(1) The four number are the total number of solutions, the length of that solution, the number of steps it took to reduce the shown examples, and a prior based on the binary trees.

The general thing to do is to run pychuriso and get a bunch of solutions. Then you can sort them by some criteria (like length, or length plus runtime) to find the "best" solutions (there's a script in postprocessing to do this).

(2) all of the "show" lines are items where pychuriso just computes some thing you want to see and it shows you the output in combinators and then the set of symbols that is equal to. In this case, this particular mapping of symbols to combinators does not give you a sensible meaning for (odd (succ four)). 

(3) Yes, it keeps searching for more and more solutions, and it's not guaranteed to find the shortest first, although it often does. So, you should save them to a file and sort (by whatever criterion you want) to find the "best."

**Comment by ischlag** [comment]
Thanks for clarifying!
